#!/bin/sh
python $ZEROVM_ROOT/ns_server.py 3 54321&
sleep 0.05
$ZEROVM_ROOT/zerovm -QPsT`pwd`/ztrace1.txt netcopy1.manifest&
$ZEROVM_ROOT/zerovm -QPsT`pwd`/ztrace2.txt netcopy2.manifest&
$ZEROVM_ROOT/zerovm -QPsT`pwd`/ztrace3.txt netcopy3.manifest
