#!/bin/bash

python $ZEROVM_ROOT/ns_server.py 10 54321&
sleep 0.05
$ZEROVM_ROOT/zerovm copy1.manifest&
$ZEROVM_ROOT/zerovm copy2.manifest&
$ZEROVM_ROOT/zerovm copy3.manifest&
$ZEROVM_ROOT/zerovm copy4.manifest&
$ZEROVM_ROOT/zerovm copy5.manifest&
$ZEROVM_ROOT/zerovm copy6.manifest&
$ZEROVM_ROOT/zerovm copy7.manifest&
$ZEROVM_ROOT/zerovm copy8.manifest&
$ZEROVM_ROOT/zerovm copy9.manifest&
$ZEROVM_ROOT/zerovm copy10.manifest
