#!/bin/sh
#SHOULD BE RUN FROM THE "SANDBOX ROOT FOLDER/native_client/"
#----------------------------------------------------------

#temporary! "-Llibs2kill" option added to avoid linker error "ld: cannot find library"
#all sandbox libs are moved to one folder: "libs2kill"
#how to make ld to take libs from original locations? 
g++-4.4 -o scons-out/opt-linux-x86-64/obj/src/trusted/service_runtime/sel_ldr -Wl,-z,noexecstack -m64 -L/usr/lib64 -pie -Wl,-z,relro -Wl,-z,now -Wl,-rpath=/home/bigcrunch/sandbox_hack/native_client/scons-out/opt-linux-x86-64/lib scons-out/opt-linux-x86-64/obj/src/trusted/service_runtime/sel_main.o -L/usr/lib -Lscons-out/opt-linux-x86-64/lib -L/home/bigcrunch/sandbox_hack/ppapi/native_client/scons-out/opt-linux-x86-64/lib -lsel -lenv_cleanser -lnacl_error_code -lmanifest_proxy -lsimple_service -lthread_interface -lgio_wrapped_desc -lnonnacl_srpc -lnrd_xfer -lnacl_perf_counter -lnacl_base -limc -lcontainer -lnacl_fault_inject -lplatform -lplatform_qual_lib -lncvalidate_x86_64 -lncval_reg_sfi_x86_64 -lnccopy_x86_64 -lnc_decoder_x86_64 -lnc_opcode_modeling_x86_64 -lncval_base_x86_64 -lplatform -lgio -ldebug_stub_init -lgdb_rsp -ldebug_stub -lrt -lpthread -lcrypto -ldl -Llibs2kill

#via compiler
#g++-4.4 -o scons-out/opt-linux-x86-64/obj/src/trusted/service_runtime/sel_ldr -Wl,-z,noexecstack -m64 -L/usr/lib64 -pie -Wl,-z,relro -Wl,-z,now -Wl,-rpath=/home/bigcrunch/sandbox_hack/native_client/scons-out/opt-linux-x86-64/lib scons-out/opt-linux-x86-64/obj/src/trusted/service_runtime/sel_main.o -L/usr/lib -Lscons-out/opt-linux-x86-64/lib -L/home/bigcrunch/sandbox_hack/ppapi/native_client/scons-out/opt-linux-x86-64/lib -lsel -lenv_cleanser -lnacl_error_code -lmanifest_proxy -lsimple_service -lthread_interface -lgio_wrapped_desc -lnonnacl_srpc -lnrd_xfer -lnacl_perf_counter -lnacl_base -limc -lcontainer -lnacl_fault_inject -lplatform -lplatform_qual_lib -lncvalidate_x86_64 -lncval_reg_sfi_x86_64 -lnccopy_x86_64 -lnc_decoder_x86_64 -lnc_opcode_modeling_x86_64 -lncval_base_x86_64 -lplatform -lgio -ldebug_stub_init -lgdb_rsp -ldebug_stub -lrt -lpthread -lcrypto -ldl

# via linker
#ld_old --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=both -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -o scons-out/opt-linux-x86-64/obj/src/trusted/service_runtime/sel_ldr -z relro /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.4.3/crtbeginS.o -L/usr/lib64 -L/usr/lib -Lscons-out/opt-linux-x86-64/lib -L/home/bigcrunch/nativeclient/ppapi/native_client/scons-out/opt-linux-x86-64/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -z noexecstack -z relro -z now -rpath=/home/bigcrunch/nativeclient/native_client/scons-out/opt-linux-x86-64/lib scons-out/opt-linux-x86-64/obj/src/trusted/service_runtime/sel_main.o -lsel -lenv_cleanser -lnacl_error_code -lmanifest_proxy -lsimple_service -lthread_interface -lgio_wrapped_desc -lnonnacl_srpc -lnrd_xfer -lnacl_perf_counter -lnacl_base -limc -lcontainer -lnacl_fault_inject -lplatform -lplatform_qual_lib -lncvalidate_x86_64 -lncval_reg_sfi_x86_64 -lnccopy_x86_64 -lnc_decoder_x86_64 -lnc_opcode_modeling_x86_64 -lncval_base_x86_64 -lplatform -lgio -ldebug_stub_init -lgdb_rsp -ldebug_stub -lrt -lpthread -lcrypto -ldl -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/4.4.3/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/crtn.o
