#!/bin/bash

python $ZEROVM_ROOT/ns_server.py 4 54321&
usleep 50
$ZEROVM_ROOT/zerovm copy1.manifest&
$ZEROVM_ROOT/zerovm copy2.manifest&
$ZEROVM_ROOT/zerovm copy3.manifest&
$ZEROVM_ROOT/zerovm copy4.manifest
pkill -9 -f ns_server.py

